import type { Metadata } from 'next'
import '@wowjob/ui/reset.css'
import '@wowjob/ui/all.css'
import '@wowjob/ui/ui.css'
import { Flex } from '@wowjob/ui'
import { CSSDevelopment } from './css-devevelopment'
import { CSSProduction } from './css-production'

export const metadata: Metadata = {
  title: 'Websocket trades',
  description: 'Generated by Marian Zburlea with wowjob UI',
}

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode
}>) => {
  return (
    <html lang="en">
      <body id="wowjob-ui">
        <Flex
          mobile={{ gap: 16, padding: 8 }}
          tablet={{ gap: 32, padding: 16 }}
          desktop={{ gap: 48, padding: 24 }}
        >
          {process.env.NODE_ENV !== 'production' && (
            <CSSDevelopment>{children}</CSSDevelopment>
          )}

          {process.env.NODE_ENV === 'production' && (
            <CSSProduction>{children}</CSSProduction>
          )}
        </Flex>
      </body>
    </html>
  )
}

export default RootLayout
